name: Greetings

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]
  workflow_dispatch:
  
# Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
