name: Greetings

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]
  workflow_dispatch:
    inputs:
      action:
        type: choice
        required: true
        description: 'Scegliere che tipo di azione si vuole operare'
        options:
        - install
        - upgrade
        - check
  
# Allows external webhook trigger
  repository_dispatch:
    types:
      - greetings

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    - name: stampo scelta
      env:
        scelta: ${{ github.event.client_payload.action }}
      run: |
        echo $scelta
